prog:main.o perso.o menu.o 
	gcc main.o perso.o menu.o -o prog -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf
main.o:main.c 
	gcc -c main.c -g
perso.o:perso.c
	gcc -c perso.c -g
menu.o:menu.c
	gcc -c menu.c -g	


